### Pandas tutorial

1. Exploring a dataframe and changing column data types

In [139]:
import re
import pandas as pd
import numpy as np

print("version:", pd.__version__)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_rows', None)

KBO = pd.read_csv(
    "./data/kbo.csv", encoding='utf-8'
)

version: 2.2.3

In [3]:
KBO.tail(3)

,선수명,등번호,생년월일,포지션,경력,입단 계약금,연봉,지명순위,입단년도,team,신장,체중,BMI
910,하영민,No.50,1995년 05월 07일,투수(우투우타),광주수창초-진흥중-진흥고-히어로즈,15000만원,8000만원,14 넥센 2차 1라운드 4순위,14넥센,키움 히어로즈,183,74,22.096808
911,헤이수스,No.54,1996년 12월 10일,투수(좌투좌타),베네수엘라 Juanita Hernandez(고),NaN,600000달러,24 키움 자유선발,24키움,키움 히어로즈,192,104,28.211806
912,후라도,No.75,1996년 01월 30일,투수(우투우타),파나마 San Judas Tadeo(고),NaN,1200000달러,23 키움 자유선발,23키움,키움 히어로즈,187,109,31.170465

In [23]:
cols = KBO.columns.to_list()
cols

['선수명',
 '등번호',
 '생년월일',
 '포지션',
 '경력',
 '입단 계약금',
 '연봉',
 '지명순위',
 '입단년도',
 'team',
 '신장',
 '체중',
 'BMI']

In [29]:
# sum by rows
KBO.isnull().sum(axis=1)
# sum by columns
KBO.isnull().sum(axis=0)

선수명         0
등번호         0
생년월일        0
포지션         0
경력          0
입단 계약금    128
연봉         38
지명순위        1
입단년도      163
team        0
신장          0
체중          0
BMI         0
dtype: int64

In [76]:
KBO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913 entries, 0 to 912
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   선수명        913 non-null    object
 1   등번호        913 non-null    object
 2   생년월일       913 non-null    object
 3   포지션        913 non-null    object
 4   경력         913 non-null    object
 5   입단 계약금     785 non-null    object
 6   연봉         875 non-null    object
 7   지명순위       912 non-null    object
 8   입단년도       750 non-null    object
 9   team       913 non-null    object
 10  신장         913 non-null    int64
 11  체중         913 non-null    int64
 12  BMI        913 non-null    float64
 13  연봉(만원)     913 non-null    int64
 14  연봉(달러)     913 non-null    int64
 15  birth      913 non-null    datetime64[ns]
 16  투수(우투우타)   913 non-null    bool
 17  내야수(우투우타)  913 non-null    bool
 18  외야수(우투좌타)  913 non-null    bool
 19  투수(좌투좌타)   913 non-null    bool
 20  포수(우투우타)   913 non-null    bool
 21  내야수(우투좌타)  913 non-null    bool
 22  외야수(좌투좌타)  913 non-null    bool
 23  투수(우언우타)   913 non-null    bool
 24  외야수(우투우타)  913 non-null    bool
 25  투수(좌투우타)   913 non-null    bool
 26  내야수(좌투좌타)  913 non-null    bool
 27  투수(우투양타)   913 non-null    bool
 28  포수(우투좌타)   913 non-null    bool
 29  투수(우투좌타)   913 non-null    bool
 30  외야수(우투양타)  913 non-null    bool
 31  투수(우언좌타)   913 non-null    bool
 32  내야수(우투양타)  913 non-null    bool
 33  외야수(좌투우타)  913 non-null    bool
 34  포수(우투양타)   913 non-null    bool
dtypes: bool(19), datetime64[ns](1), float64(1), int64(4), object(10)
memory usage: 131.2+ KB

In [75]:
KBO.dtypes

선수명                  object
등번호                  object
생년월일                 object
포지션                  object
경력                   object
입단 계약금               object
연봉                   object
지명순위                 object
입단년도                 object
team                 object
신장                    int64
체중                    int64
BMI                 float64
연봉(만원)                int64
연봉(달러)                int64
birth        datetime64[ns]
투수(우투우타)               bool
내야수(우투우타)              bool
외야수(우투좌타)              bool
투수(좌투좌타)               bool
포수(우투우타)               bool
내야수(우투좌타)              bool
외야수(좌투좌타)              bool
투수(우언우타)               bool
외야수(우투우타)              bool
투수(좌투우타)               bool
내야수(좌투좌타)              bool
투수(우투양타)               bool
포수(우투좌타)               bool
투수(우투좌타)               bool
외야수(우투양타)              bool
투수(우언좌타)               bool
내야수(우투양타)              bool
외야수(좌투우타)              bool
포수(우투양타)               bool
dtype: object

In [47]:
KBO.dtypes.value_counts()

object     10
int64       2
float64     1
Name: count, dtype: int64

2. Add ["back_number", "date", "deposit", "income", ...] columns

In [2]:
pos = KBO['포지션'].unique()
pos

array(['투수(우투우타)', '내야수(우투우타)', '외야수(우투좌타)', '투수(좌투좌타)', '포수(우투우타)',
       '내야수(우투좌타)', '외야수(좌투좌타)', '투수(우언우타)', '외야수(우투우타)', '투수(좌투우타)',
       '내야수(좌투좌타)', '투수(우투양타)', '포수(우투좌타)', '투수(우투좌타)', '외야수(우투양타)',
       '투수(우언좌타)', '내야수(우투양타)', '외야수(좌투우타)', '포수(우투양타)'], dtype=object)

To create a new column based on the values of an existing column, and assign True if the value exists in that column, and False otherwise,

In [74]:
KBO[pos] = False
for p in pos:
    KBO[p] = KBO['포지션'] == p
KBO.tail(3)

,선수명,등번호,생년월일,포지션,경력,입단 계약금,연봉,지명순위,입단년도,team,신장,체중,BMI,연봉(만원),연봉(달러),birth,투수(우투우타),내야수(우투우타),외야수(우투좌타),투수(좌투좌타),포수(우투우타),내야수(우투좌타),외야수(좌투좌타),투수(우언우타),외야수(우투우타),투수(좌투우타),내야수(좌투좌타),투수(우투양타),포수(우투좌타),투수(우투좌타),외야수(우투양타),투수(우언좌타),내야수(우투양타),외야수(좌투우타),포수(우투양타)
910,하영민,No.50,1995년 05월 07일,투수(우투우타),광주수창초-진흥중-진흥고-히어로즈,15000만원,8000만원,14 넥센 2차 1라운드 4순위,14넥센,키움 히어로즈,183,74,22.096808,8000,0,1995-05-07,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
911,헤이수스,No.54,1996년 12월 10일,투수(좌투좌타),베네수엘라 Juanita Hernandez(고),NaN,600000달러,24 키움 자유선발,24키움,키움 히어로즈,192,104,28.211806,0,600000,1996-12-10,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
912,후라도,No.75,1996년 01월 30일,투수(우투우타),파나마 San Judas Tadeo(고),NaN,1200000달러,23 키움 자유선발,23키움,키움 히어로즈,187,109,31.170465,0,1200000,1996-01-30,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [140]:
# dataframe[] -> Series, dataframe[[]] -> Dataframe
KBO['화폐 단위'] = KBO['연봉'].str.extract(r'(\D+)$')
# 
KBO['입단 계약금'] = KBO['입단 계약금'].fillna(0)

crcy = KBO['화폐 단위'].unique()[~pd.isna(KBO['화폐 단위'].unique())]

for c in crcy:
    KBO[f'연봉({c})'] = KBO['연봉'].str.extract(fr'(\d+)(?={c})').fillna(0).astype(int)
    # KBO['연봉(달러)'] = KBO['연봉'].str.extract(r'(\d+)(?=달러)').fillna(0).astype(int)
    KBO[f'입단 계약금({c})'] = KBO['입단 계약금'].str.extract(fr'(\d+)(?={c})').fillna(0).astype(int)
    # KBO['입단 계약금(달러)'] = KBO['입단 계약금'].str.extract(r'(\d+)(?=달러)').fillna(0).astype(int)
KBO.tail(3)

/tmp/ipykernel_29383/2662856266.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  KBO[f'입단 계약금({c})'] = KBO['입단 계약금'].str.extract(fr'(\d+)(?={c})').fillna(0).astype(int)

,선수명,등번호,생년월일,포지션,경력,입단 계약금,연봉,지명순위,입단년도,team,신장,체중,BMI,화폐 단위,연봉(만원),입단 계약금(만원),연봉(달러),입단 계약금(달러),연봉(엔),입단 계약금(엔)
910,하영민,No.50,1995년 05월 07일,투수(우투우타),광주수창초-진흥중-진흥고-히어로즈,15000만원,8000만원,14 넥센 2차 1라운드 4순위,14넥센,키움 히어로즈,183,74,22.096808,만원,8000,15000,0,0,0,0
911,헤이수스,No.54,1996년 12월 10일,투수(좌투좌타),베네수엘라 Juanita Hernandez(고),0,600000달러,24 키움 자유선발,24키움,키움 히어로즈,192,104,28.211806,달러,0,0,600000,0,0,0
912,후라도,No.75,1996년 01월 30일,투수(우투우타),파나마 San Judas Tadeo(고),0,1200000달러,23 키움 자유선발,23키움,키움 히어로즈,187,109,31.170465,달러,0,0,1200000,0,0,0

In [138]:
KBO

0        7000만원
1        4000만원
2        7000만원
3        7000만원
4        8000만원
5        6000만원
6        7000만원
7       13000만원
8        4000만원
9       35000만원
10       6000만원
11      40000만원
12       3000만원
13       8000만원
14       3000만원
15            0
16       4000만원
17       5000만원
18       8000만원
19       9000만원
20       3000만원
21      13000만원
22       5000만원
23      14000만원
24       3000만원
25       7000만원
26       8000만원
27       7000만원
28       9000만원
29       3000만원
30      30000만원
31     200000달러
32      50000달러
33      13000만원
34      15000만원
35            0
36            0
37       5000만원
38       4000만원
39       8000만원
40      18000만원
41            0
42       3000만원
43     100000달러
44            0
45       3000만원
46      25000달러
47      20000만원
48       9000만원
49       8000만원
50       5000만원
51            0
52      18000만원
53       7000만원
54      10000만원
55      32000만원
56       4000만원
57       4000만원
58      10000만원
59       6000만원
60       5000만원
61       8000만원
62       6000만원
63      12000만원
64      30000만원
65       3000만원
66       8000만원
67       5000만원
68       7000만원
69      11000만원
70      13000만원
71      10000만원
72       4000만원
73       5000만원
74      15000만원
75       7000만원
76      20000만원
77      10000만원
78      25000만원
79      20000만원
80       4000만원
81      15000만원
82      11000만원
83      15000만원
84       5000만원
85       5000만원
86     200000달러
87       9000만원
88      16000만원
89      13000만원
90      11000만원
91      16000만원
92       4000만원
93       9000만원
94      14000만원
95       4000만원
96      13000만원
97       2000만원
98            0
99      11000만원
100           0
101      6000만원
102           0
103     11000만원
104      4000만원
105      6000만원
106      7000만원
107      7000만원
108      4000만원
109      8000만원
110     17000만원
111      5000만원
112     10000만원
113     20000만원
114           0
115     11000만원
116      3000만원
117     11000만원
118     11000만원
119      2000만원
120      6000만원
121      7000만원
122      3000만원
123      6000만원
124           0
125    100000달러
126      5000만원
127      7000만원
128    100000달러
129     13000만원
130     33000만원
131      4000만원
132      3000만원
133     15000만원
134      3000만원
135     15000만원
136     11000만원
137     40000만원
138      5000만원
139           0
140           0
141      8000만원
142      3000만원
143     18000만원
144      8000만원
145     35000만원
146      3000만원
147     25000만원
148      7000만원
149     30000만원
150      8000만원
151      4000만원
152      8000만원
153      7000만원
154     35000만원
155     10000만원
156      4000만원
157     22000만원
158      4000만원
159      4000만원
160      4000만원
161     20000만원
162      7000만원
163      3000만원
164           0
165      9000만원
166      8000만원
167      5000만원
168      7000만원
169      8000만원
170     11000만원
171     13000만원
172     30000만원
173     28000만원
174      5000만원
175           0
176    100000달러
177      3000만원
178     10000만원
179      8000만원
180      8000만원
181     23000만원
182      8000만원
183      4000만원
184     20000만원
185      5000만원
186      3000만원
187      7000만원
188     27000만원
189      3000만원
190     11000만원
191     25000만원
192      5000만원
193      5000만원
194           0
195     25000만원
196      4000만원
197     20000만원
198     20000만원
199      5000만원
200      4000만원
201     10000만원
202      5000만원
203      4000만원
204           0
205     10000만원
206           0
207     15000만원
208      6000만원
209      8000만원
210      3000만원
211      4000만원
212           0
213      6000만원
214     11000만원
215      3000만원
216           0
217      5000만원
218     10000만원
219      5000만원
220      7000만원
221     15000만원
222     10000만원
223     15000만원
224      5000만원
225           0
226      3000만원
227     12000만원
228           0
229    300000달러
230    100000달러
231           0
232     28000만원
233      4000만원
234           0
235     60000만원
236      7000만원
237     15000만원
238     13000만원
239     11000만원
240     10000만원
241      3000만원
242      7000만원
243      3000만원
244      7000만원
245           0
246      4000만원
247     30000만원
248      3000만원
249           0
250     10000만원
251      6000만원
252      7000만원
253           0
254     12000만원
255           0
256           0
257     10000만원
258      5000만원
259     35000만원
260    300000달러
261      6000만원
262      5000만원
263      6000만원
264      5000만원
265           0
266      5000만원
267      8000만원
268      4000만원
269     20000만원
270      8000만원
271      7000만원
272     30000만원
273      3000만원
274           0
275      8000만원
276      7000만원
277     35000만원
278      6000만원
279     12000만원
280     13000만원
281     10000만원
282      5000만원
283      3000만원
284      8000만원
285     10000만원
286     15000만원
287     20000만원
288     20000만원
289     15000만원
290     16000만원
291      6000만원
292      3000만원
293     35000만원
294           0
295      3000만원
296      6000만원
297    100000달러
298    100000달러
299      3000만원
300      7000만원
301     11000만원
302      4000만원
303           0
304     14000만원
305           0
306      5000만원
307     20000만원
308      6000만원
309      6000만원
310     14000만원
311           0
312      6000만원
313      5000만원
314           0
315      6000만원
316      3000만원
317           0
318     13000만원
319    200000달러
320      9000만원
321      3000만원
322      4000만원
323      3000만원
324     15000만원
325      5000만원
326      7000만원
327      6000만원
328      8000만원
329           0
330      7000만원
331     27000만원
332      4000만원
333      5000만원
334     35000만원
335     10000만원
336      6000만원
337     20000만원
338      8000만원
339     10000만원
340     14000만원
341      7000만원
342           0
343      6000만원
344      7000만원
345           0
346      6000만원
347           0
348     10000만원
349           0
350     10000만원
351     14000만원
352      7000만원
353           0
354      8000만원
355      8000만원
356     18000만원
357      3000만원
358     20000만원
359           0
360      5000만원
361     13000만원
362     14000만원
363      7000만원
364      3000만원
365      6000만원
366     45000만원
367     15000만원
368     13000만원
369     15000만원
370      8000만원
371      4000만원
372           0
373           0
374     30000만원
375      3000만원
376      9000만원
377     11000만원
378      6000만원
379      3000만원
380     28000만원
381      7000만원
382           0
383     22000만원
384      3000만원
385           0
386           0
387      8000만원
388      5000만원
389    100000달러
390     13000만원
391      5000만원
392     43000만원
393      7000만원
394     23000만원
395           0
396      9000만원
397     30000만원
398      6000만원
399      5000만원
400     15000만원
401    100000달러
402      4000만원
403     36000만원
404      9000만원
405           0
406     17000만원
407     12000만원
408      7000만원
409     13000만원
410      6000만원
411      7000만원
412           0
413     23000만원
414           0
415      8000만원
416     12000만원
417      6000만원
418     23000만원
419      8000만원
420     13000만원
421           0
422      8000만원
423      4000만원
424      8000만원
425      5000만원
426      3000만원
427      4000만원
428     16000만원
429     11000만원
430      3000만원
431      6000만원
432      5000만원
433      8000만원
434           0
435      6000만원
436     20000만원
437     10000만원
438     20000만원
439     12000만원
440      4000만원
441      4000만원
442           0
443           0
444      7000만원
445     30000만원
446      7000만원
447     10000만원
448           0
449      3000만원
450      8000만원
451           0
452    250000달러
453     16000만원
454      1000만원
455     10000만원
456     10000만원
457      9000만원
458      4000만원
459      6000만원
460      7000만원
461      9000만원
462     11000만원
463     20000만원
464      3000만원
465     50000만원
466      3000만원
467     14000만원
468      5000만원
469     10000만원
470      7000만원
471     10000만원
472           0
473      5000만원
474     15000만원
475      4000만원
476     10000만원
477     35000만원
478    100000달러
479      4000만원
480      5000만원
481     18000만원
482      9000만원
483     10000만원
484     10000만원
485      5000만원
486      9000만원
487      6000만원
488      2000만원
489      5000만원
490     10000만원
491     20000만원
492     10000만원
493      4000만원
494      3000만원
495      4000만원
496           0
497           0
498     15000만원
499      4000만원
500     18000만원
501      8000만원
502      8000만원
503           0
504           0
505           0
506     20000만원
507      9000만원
508      8000만원
509      4000만원
510     20000만원
511      6000만원
512     25000만원
513     13000만원
514      4000만원
515      6000만원
516           0
517      8000만원
518           0
519      4000만원
520      6000만원
521      6000만원
522     13000만원
523     20000만원
524     10000만원
525      6000만원
526      5000만원
527      7000만원
528      4000만원
529     13000만원
530      3000만원
531      5000만원
532     10000만원
533     10000만원
534           0
535      8000만원
536      3000만원
537     30000만원
538      7000만원
539      8000만원
540      7000만원
541           0
542           0
543           0
544      3000만원
545      7000만원
546           0
547      7000만원
548      7000만원
549           0
550     15000만원
551           0
552     15000만원
553      5000만원
554           0
555           0
556           0
557      9000만원
558      6000만원
559           0
560     25000만원
561     10000만원
562     13000만원
563     15000만원
564     37000만원
565     15000만원
566     50000만원
567      8000만원
568    100000달러
569      9000만원
570      6000만원
571     20000만원
572      8000만원
573      6000만원
574     11000만원
575      8000만원
576      8000만원
577     10000만원
578    150000달러
579           0
580           0
581           0
582      3000만원
583     15000만원
584           0
585      6000만원
586      6000만원
587      3000만원
588     30000만원
589     25000만원
590      4000만원
591      2000만원
592      6000만원
593           0
594      4000만원
595      3000만원
596      8000만원
597     45000만원
598     20000만원
599      3000만원
600      5000만원
601     18000만원
602     12000만원
603      3000만원
604      3000만원
605           0
606     15000만원
607      6000만원
608           0
609     10000만원
610     11000만원
611      3000만원
612     30000만원
613     10000만원
614      3000만원
615      7000만원
616      3000만원
617     10000만원
618      5000만원
619      3000만원
620     15000만원
621           0
622           0
623     12000만원
624      4000만원
625     15000만원
626      3000만원
627     11000만원
628           0
629     25000만원
630           0
631      8000만원
632      6000만원
633     18000만원
634     23000만원
635           0
636     16000만원
637      7000만원
638      8000만원
639           0
640           0
641      3000만원
642     11000만원
643      7000만원
644      4000만원
645     15000만원
646           0
647      5000만원
648     20000만원
649     20000만원
650      3000만원
651     50000만원
652           0
653      3000만원
654           0
655      3000만원
656           0
657      3000만원
658      5000만원
659           0
660     16000만원
661     20000만원
662     25000만원
663     50000만원
664      3000만원
665     15000만원
666     70000달러
667      4000만원
668      8000만원
669     10000만원
670      6000만원
671      7000만원
672           0
673           0
674           0
675      5000만원
676     10000만원
677      3000만원
678           0
679     22000만원
680      3000만원
681     18000만원
682      5000만원
683           0
684     12000달러
685      3000만원
686     11000만원
687      9000만원
688      5000만원
689      6000만원
690      8000만원
691      3000만원
692     24000만원
693     11000만원
694      4000만원
695           0
696      4000만원
697      6000만원
698     15000만원
699      4000만원
700      8000만원
701      6000만원
702     25000만원
703     10000만원
704      5000만원
705      7000만원
706      7000만원
707      9000만원
708      7000만원
709      8000만원
710     18000만원
711     10000만원
712      7000만원
713     10000만원
714      8500만원
715      9000만원
716      8000만원
717     15000만원
718      8000만원
719      4000만원
720      5000만원
721           0
722      6000만원
723           0
724      6000만원
725    100000달러
726    200000달러
727     30000만원
728           0
729     11000만원
730     18000만원
731      3000만원
732     11000만원
733      8000만원
734     35000만원
735      6000만원
736      7000만원
737      3000만원
738      3000만원
739           0
740      9000만원
741      6000만원
742      7000만원
743      5000만원
744      4000만원
745     20000만원
746      4000만원
747      3000만원
748      3000만원
749      4000만원
750     15000만원
751      3000만원
752      3000만원
753      9000만원
754     15000만원
755     30000만원
756           0
757           0
758           0
759     15000만원
760     25000만원
761     10000만원
762      3000만원
763           0
764    140000달러
765           0
766     10000만원
767      8000만원
768      6000만원
769     10000만원
770     10000만원
771     16000만원
772      6000만원
773     12000만원
774           0
775           0
776           0
777      5000만원
778      4000만원
779     15000만원
780      3000만원
781     15000만원
782      3000만원
783      8000만원
784      3000만원
785      3000만원
786      8000만원
787      8000만원
788      6000만원
789     16000만원
790     10000만원
791      6000만원
792      5000만원
793     25000만원
794     10000만원
795     20000만원
796     10000만원
797     13000만원
798     10000만원
799           0
800      5000만원
801      7000만원
802     10000만원
803     45000만원
804      6000만원
805     10000만원
806      6000만원
807      4000만원
808     15000만원
809      7000만원
810      8000만원
811     14000만원
812     10000만원
813      4000만원
814      5000만원
815      8000만원
816     14000만원
817           0
818      4000만원
819     10000만원
820      8000만원
821      6000만원
822      6000만원
823      5000만원
824    130000달러
825      5000만원
826    200000달러
827      5000만원
828      7000만원
829      4000만원
830      7000만원
831      7000만원
832     22000만원
833     13000만원
834      2000만원
835     15000만원
836      8000만원
837      7000만원
838           0
839     13000만원
840      6000만원
841      5000만원
842      9000만원
843      8000만원
844     20000만원
845      7000만원
846      5000만원
847      3000만원
848      2000만원
849      7000만원
850      8000만원
851      5000만원
852      8000만원
853     13000만원
854      6000만원
855           0
856      8000만원
857      4000만원
858      5000만원
859           0
860           0
861      3000만원
862      9000만원
863     20000만원
864      5000만원
865     13000만원
866      4000만원
867      7000만원
868           0
869      4000만원
870      3000만원
871     12000만원
872      8000만원
873      7000만원
874      5000만원
875      9000만원
876           0
877      3000만원
878      3000만원
879      9000만원
880     11000만원
881      6000만원
882      5000만원
883           0
884     11000만원
885      6000만원
886           0
887      6000만원
888      5000만원
889      7000만원
890           0
891     10000만원
892     13000만원
893     13000만원
894     11000만원
895     15000만원
896     43000만원
897      4000만원
898     20000만원
899     11000만원
900     90000만원
901     21000만원
902     30000만원
903     25000만원
904     15000만원
905     10000만원
906      8000만원
907      5000만원
908     18000만원
909      6000만원
910     15000만원
911           0
912           0
Name: 입단 계약금, dtype: object

In [113]:
np.isnan(crcy[2])
# np.isnan(KBO['화폐 단위'].unique().to_numpy())

np.True_

In [127]:
type(crcy[2])
crcy == np.nan
pd.isna(crcy[2])
~pd.isna(KBO['화폐 단위'].unique())
KBO['화폐 단위'].unique()[~pd.isna(KBO['화폐 단위'].unique())]

array(['만원', '달러', '엔'], dtype=object)

In [80]:
KBO['birth'] = pd.to_datetime(
    KBO['생년월일'].str.replace(r'년|월|일', '-', regex=True).str.rstrip('-').str.replace(r' ', '', regex=True),
    format='%Y-%m-%d'
)
KBO.tail(3)

,선수명,등번호,생년월일,포지션,경력,입단 계약금,연봉,지명순위,입단년도,team,신장,체중,BMI,연봉(만원),연봉(달러),입단 계약금(만원),입단 계약금(달러),birth
910,하영민,No.50,1995년 05월 07일,투수(우투우타),광주수창초-진흥중-진흥고-히어로즈,15000만원,8000만원,14 넥센 2차 1라운드 4순위,14넥센,키움 히어로즈,183,74,22.096808,8000,0,15000,0,1995-05-07
911,헤이수스,No.54,1996년 12월 10일,투수(좌투좌타),베네수엘라 Juanita Hernandez(고),NaN,600000달러,24 키움 자유선발,24키움,키움 히어로즈,192,104,28.211806,0,600000,0,0,1996-12-10
912,후라도,No.75,1996년 01월 30일,투수(우투우타),파나마 San Judas Tadeo(고),NaN,1200000달러,23 키움 자유선발,23키움,키움 히어로즈,187,109,31.170465,0,1200000,0,0,1996-01-30

In [103]:
KBO['연봉'].str.contains('달러|만원', regex=True)
KBO['화폐 단위'] = KBO['연봉'].str.extract(r'(\D+)$')
KBO['화폐 단위'].unique()

array(['만원', '달러', nan, '엔'], dtype=object)

In [101]:
KBO[KBO['입단 계약금(nan)'] != 0]

Empty DataFrame
Columns: [선수명, 등번호, 생년월일, 포지션, 경력, 입단 계약금, 연봉, 지명순위, 입단년도, team, 신장, 체중, BMI, 화폐 단위, 연봉(만원), 입단 계약금(만원), 연봉(달러), 입단 계약금(달러), 연봉(nan), 입단 계약금(nan), 연봉(엔), 입단 계약금(엔)]
Index: []

In [ ]:
KBO['등번호'].str.extract(r'')

In [43]:
dd = '1995년 05월 07일 1996년 05월 07일'
ii = '8000만원'

tmp = re.search(r'(\d{4})년 (\d{2})월 (\d{2})일', dd)
tmp.group(3)

tmp = re.search(r'[0-9]+', ii)
tmp.group(0)

'8000'

In [3]:
KBO['back_number'] = None
KBO.tail(3)

,선수명,등번호,생년월일,포지션,경력,입단 계약금,연봉,지명순위,입단년도,team,신장,체중,BMI,back_number
910,하영민,No.50,1995년 05월 07일,투수(우투우타),광주수창초-진흥중-진흥고-히어로즈,15000만원,8000만원,14 넥센 2차 1라운드 4순위,14넥센,키움 히어로즈,183,74,22.096808,None
911,헤이수스,No.54,1996년 12월 10일,투수(좌투좌타),베네수엘라 Juanita Hernandez(고),NaN,600000달러,24 키움 자유선발,24키움,키움 히어로즈,192,104,28.211806,None
912,후라도,No.75,1996년 01월 30일,투수(우투우타),파나마 San Judas Tadeo(고),NaN,1200000달러,23 키움 자유선발,23키움,키움 히어로즈,187,109,31.170465,None

In [9]:
KBO.to_csv(
    './data/kbo.csv', index=False
)