### `mysql+pymysql`

`mysql+pymysql`은 SQLAlchemy에서 MySQL 데이터베이스에 연결할 때 사용하는 연결 문자열. `mysql`은 **dialect**이고, `pymysql`은 **driver**.

#### 1. **Dialect (`mysql`)**

- **Dialect**는 SQLAlchemy가 어떤 종류의 데이터베이스와 연결할지 지정하는 부분.
- `mysql`은 SQLAlchemy가 **MySQL 데이터베이스**를 사용할 때 사용하는 **dialect**입니다.
- SQLAlchemy는 다양한 데이터베이스를 지원하며, 각 데이터베이스마다 고유의 dialect가 존재. 예를 들어:
  - `postgresql` : PostgreSQL 데이터베이스
  - `sqlite` : SQLite 데이터베이스
  - `mssql` : Microsoft SQL Server

#### 2. **Driver (`pymysql`)**

- **Driver**는 SQLAlchemy가 데이터베이스와 연결할 때 사용할 **Python 라이브러리**.
- `pymysql`은 MySQL 데이터베이스와 연결할 때 사용하는 드라이버로, **Pure Python으로 작성된 MySQL 클라이언트 라이브러리**.
- SQLAlchemy는 여러 드라이버를 지원하며, MySQL과 연결할 때 `pymysql` 외에도 `mysqlclient`나 `MySQLdb` 같은 드라이버를 사용할 수 있다.

#### 3. **`mysql+pymysql`의 의미**

- `mysql+pymysql`은 **SQLAlchemy가 MySQL 데이터베이스에 연결할 때 `pymysql` 드라이버를 사용하도록 지정**.
- 예를 들어, `mysql+pymysql://username:password@localhost:3306/mydatabase`와 같은 형식으로 연결 문자열을 작성하면, SQLAlchemy는 `pymysql`을 통해 MySQL 서버에 연결.

In [26]:
import json
import pandas as pd
from sqlalchemy import create_engine

DB = "pandas_tutorial"

with open('/home/dongik/src/config.json', 'r') as config_file:
    config = json.load(config_file)['mysql'][DB]
    
username = config['username']
password = config['password']
host = config['host']
port = config['port']
database = 'pandas_tutorial'

connection_string = f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}'

engine = create_engine(connection_string)

try:
    with engine.connect() as connection:
        print("Database connection successful!")
except Exception as e:
    print(f"Database connection failed: {e}")

Database connection successful!

In [ ]:
from sqlalchemy import Column, Integer, String, DECIMAL, Date, Float, Boolean
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.ext.declarative import declarative_base



class Base(DeclarativeBase):
    pass

class KBO(Base):
    __tablename__ = "kbo"
    
    name = Column(String(20), primary_key=True)
    back_number = Column(Integer)
    birth = Column(Date)
    position = Column(String(50))
    annual_income = Column(Float)
    contract_amount = Column(Float)
    team = Column(String(20))
    height = Column(Float)
    weight = Column(Float)
    BMI = Column(Float)

In [33]:
base = Base()
base.metadata.create_all(engine)

In [27]:
kbo.columns

Index(['선수명', '등번호', '생년월일', '포지션', '경력', '입단 계약금', '연봉', '지명순위', '입단년도',
       'team', '신장', '체중', 'BMI'],
      dtype='object')

In [18]:
kbo = pd.read_csv(
    "./data/kbo.csv", encoding='utf-8'
)

In [ ]:
from sqlalchemy.orm import sessionmaker

Session = sessionmaker(bind=engine)
session = Session()

try:
    df.to_sql('my_table', con=engine, if_exists='replace', index=False)
    session.commit()
except Exception as e:
    session.rollback()
    print(f"Error: {e}")
finally:
    session.close()

In [15]:
with engine.connect() as connection:
    result = connection.execute(text("SHOW DATABASES;"))
    for row in result:
        print(row)

('bike',)
('encore',)
('information_schema',)
('mysql',)
('pandas_tutorial',)
('performance_schema',)
('sys',)
('tutorial',)

In [97]:
import requests
from bs4 import BeautifulSoup as BS

r = requests.get(
    "https://n.news.naver.com/mnews/article/003/0012907298?type=journalists"
)

import re
# 이메일 정규식
email_regex = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
email_regex = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

email=BS(r.text).findAll('span', class_='byline_s')[-1]
email.text.strip()

# 텍스트에서 이메일 찾기
email_match = re.findall(email_regex, email.text)
email_match

['odong85@newsis.com']

In [75]:
BS(r.text).findAll('span', class_='byline_s')[-1].text

'오동현 기자(odong85@newsis.com)'

In [91]:
s = '오동현 기자(odong85@newsis.com)'


# 이메일 정규식
email_regex = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'


tmp = re.findall(email_regex, s)
tmp

['odong85@newsis.com']

In [86]:
# 예시 문자열에 여러 이메일 포함
s = '오동현 기자(odong85@newsis.com)와 김영희 기자(younghee123@newsis.org)'

# 이메일 정규식
email_regex = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

# 여러 이메일을 찾기 위해 re.findall 사용
emails = re.findall(email_regex, s)

print(f"찾은 이메일: {emails}")

찾은 이메일: ['odong85@newsis.com', 'younghee123@newsis.org']

In [100]:
url = 'https://news.naver.com/'

# 
r = requests.get(url=url)
BS(r.text).findAll('div', class_='comp_journal_subscribe_comp_common')

[]

In [101]:
import requests 

url  = "https://news.naver.com/section/105"

r = requests.get(url)

from bs4 import BeautifulSoup as BS

bs = BS(r.text)

email_re = re.compile("[\w._%+-]+@[\w.-]+\.[a-zA-Z]{2,4}")
email_list = []
for x in bs.find("div", id="newsct").findAll("a"):
    if x['href'].find("article") > -1 and x['href'].find("comment") == -1:
        email_list.extend(email_re.findall(requests.get(x['href']).text))
email = list(set(email_list))

In [102]:
email

['bong9@hani.co',
 'lee.hayjune@joongang.co.kr',
 'choigj@kado.net',
 'kyung@kyunghyang.com',
 'jkim@zdnet.co.kr',
 'rini113@donga.com',
 'why@sedaily.com',
 'zoohihi@busan.com',
 'editor@sisain.co.kr',
 'dlcw@heraldcorp.com',
 'flyhighrom@news1.kr',
 'mansay@chosunbiz.com',
 'sweet@zdnet.co.kr',
 'young92@mt.co.kr',
 'hand@dgmbc.com',
 'leejh@news1.kr',
 'min@chosunbiz.com',
 'sbsm@journalist.or.kr',
 'kbs1234@kbs.co.kr',
 'jhpark@bloter.net',
 'bong9@hani.co.kr',
 'jejuflower@mt.co.kr',
 'touch@ichannela.com',
 'youforest@hankyung.com',
 'r2ver@mk.co.kr',
 'kny0621@nongmin.com',
 'blanc@hankookilbo.com',
 'jang.youngjoon@jtbc.co.kr',
 'sejoonkr@donga.com',
 'press@womennews.co.kr',
 'keephee@hankyung.com',
 'cjs@yna.co.kr',
 'leej@hani.co.kr',
 'terryus@kyunghyang.com',
 'jebo@tf.co.kr',
 'ilys123@pressian.com',
 'jeje@kormedi.com',
 'seokgu1026@jungyul.co.kr',
 'park.eunjee@joongang.co.kr',
 'go@munhwa.com',
 'moonkihoon@heraldcorp.com',
 'nahum@asiae.co.kr',
 'alwaysame@chosunbiz.com',
 'naretss@ddaily.co.kr',
 'ktkim@dt.co.kr',
 'kms@dt.co.kr',
 'poof34@hankyung.com',
 'digimon@ddaily.co.kr',
 'odong85@newsis.com',
 'hsg@fnnews.com',
 'songsta@kmib.co.kr',
 'chae@edaily.co.kr',
 'jujuk@yna.co.kr',
 'chldbskcjstk@mbn.co.kr',
 'langchemist@zdnet.co.kr',
 'jnjes6@dailian.co.kr',
 'gatozz@asiae.co.kr',
 'sje@mkinternet.com',
 'hjyoo@zdnet.co.kr',
 'nopil@hani.co.kr',
 'oh@sbs.co.kr',
 'ideaed@news1.kr',
 'boyoon@sbs.co.kr',
 'skdus3390@naver.com',
 'sby@news1.kr',
 'tjddk99@mt.co.kr',
 'sh@mbc.co.kr',
 '7rsilver@edaily.co.kr',
 'youngman@ikbc.co.kr',
 'kth08@kyunghyang.com',
 'boyondal@mk.co.kr',
 'polaris27@donga.com',
 'jung@hankyung.com',
 'enter@cbs.co.kr',
 'hozero@kyeonggi.com',
 'ur1@news1.kr',
 'eom@news1.kr',
 'friend@donga.com',
 'spicyzero@etnews.com',
 'anaki@hani.co.kr',
 'jh7253@zdnet.co.kr',
 'writer@yna.co.kr',
 'yesno@jtbc.co.kr',
 'yheyin@daejonilbo.com',
 'moonh@sisajournal.com',
 'yjjoe@fnnews.com',
 'dongwon@jibs.co.kr',
 'jungha98@hani.co.kr',
 'jiw3061@asiae.co.kr',
 'paikshow@zdnet.co.kr',
 'monarch@fnnews.com',
 'thankyou@kbs.co.kr',
 'kgy@chosun.com',
 'pearzoo@imaeil.com',
 'sooya@segye.com',
 'hyoink@chosun.com',
 '8823@kyunghyang.com',
 'ljh4749@dailian.co.kr',
 'jskim@bizwatch.co.kr',
 'juseok@newsis.com',
 'cho84@news1.kr',
 'chaezero@tf.co.kr',
 'jebo@cbs.co.kr',
 'leciel711@naver.com',
 'xlomin@edaily.co.kr',
 'moon@ddaily.co.kr',
 'che@hani.co.kr',
 'firstblood@zdnet.co.kr',
 'hjsong@joseilbo.com',
 'parksy@ytn.co.kr',
 'lhn@chosun.com',
 'camlee21@naver.com',
 'juckys@thescoop.co.kr',
 'omme@kwnews.co.kr',
 'cjb.eon@gmail.com',
 'kdw@inews24.com',
 'sh04khk@zdnet.co.kr',
 'jylee@jmbc.co.kr',
 'iam@etnews.com',
 'park@heraldcorp.com',
 'kang39@chosun.com',
 'pjseok@newstapa.org',
 'jangdoree@gmail.com',
 'cs86@ddaily.co.kr']

In [113]:
for x in bs.find("div", id="newsct").findAll('a'):
    break

bs.find("div", id="newsct").findAll('a')[-4]

In [125]:
bs.find("div", id="newsct").findAll('a')[-5]

<a class="col2_banner_link" data-clk="asidebanner3" href="https://news.naver.com/main/ombudsman/guidecenter.naver?mid=omb">
<img alt="" class="_LAZY_LOADING _LAZY_LOADING_INIT_HIDE" data-src="https://imgnews.pstatic.net/image/upload/item/2023/06/23/195439840_banner_24hours.png" height="80" style="display: none;" width="300"/>
<div class="blind">
<strong>뉴스 기사와 댓글로 인한 문제 발생 시 24시간 센터로 접수해주세요</strong>
<p></p>
</div>
</a>

In [127]:
import os

os.listdir('../data/smallmarket')

['소상공인시장진흥공단_상가(상권)정보_경남_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_경북_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_대전_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_인천_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_경기_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_세종_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_서울_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_대구_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_전남_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_제주_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_충남_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_충북_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_전북_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_강원_202409.csv',
 '[필독]파일열람방법.txt',
 '소상공인시장진흥공단_상가(상권)정보_광주_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_울산_202409.csv',
 '소상공인시장진흥공단_상가(상권)정보_부산_202409.csv']

In [131]:
import pandas as pd

df = pd.read_csv(
    '../data/smallmarket/소상공인시장진흥공단_상가(상권)정보_서울_202409.csv', encoding='utf-8'
)
df.columns

/tmp/ipykernel_31364/3485074446.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [140]:
pd.set_option('display.max_columns', None)
# df.tail(3)

df.loc[df['상권업종중분류명'] == '한식']
# df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
1,MA010120220805430767,토끼정,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,한식 일반 음식점업,11,서울특별시,11500,강서구,11500603,가양1동,1150010500,마곡동,1150010500107740012,1,대지,774,12.0,서울특별시 강서구 마곡동 774-12,1.150032e+11,서울특별시 강서구 마곡동로,55.0,NaN,1150010500107740012000001,마커스빌딩,서울특별시 강서구 마곡동로 55,157805,7802,NaN,2,NaN,126.833022,37.560053
2,MA010120220805430797,가배차,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,한식 일반 음식점업,11,서울특별시,11710,송파구,11710580,송파1동,1171010400,송파동,1171010400101430002,1,대지,143,2.0,서울특별시 송파구 송파동 143-2,1.171031e+11,서울특별시 송파구 가락로,209.0,NaN,1171010400101430002012823,사이언스빌딩,서울특별시 송파구 가락로 209,138852,5663,NaN,1,NaN,127.116136,37.507170
9,MA0101202210A0037544,영자's곱창,NaN,I2,음식,I201,한식,I20109,곱창 전골/구이,I56111,한식 일반 음식점업,11,서울특별시,11215,광진구,11215760,중곡3동,1121510100,중곡동,1121510100101690021,1,대지,169,21.0,서울특별시 광진구 중곡동 169-21,1.121530e+11,서울특별시 광진구 면목로,172.0,NaN,1121510100101690021003140,NaN,서울특별시 광진구 면목로 172,143900,4904,NaN,1,NaN,127.082832,37.568503
18,MA010120220805431023,숯불에닭,NaN,I2,음식,I201,한식,I20110,닭/오리고기 구이/찜,I56111,한식 일반 음식점업,11,서울특별시,11470,양천구,11470611,신월7동,1147010300,신월동,1147010300109710004,1,대지,971,4.0,서울특별시 양천구 신월동 971-4,1.147031e+11,서울특별시 양천구 지양로,60.0,NaN,1147010300109710004007555,NaN,서울특별시 양천구 지양로 60,158846,8040,NaN,1,NaN,126.834524,37.520990
26,MA010120220805432074,돈통마늘보쌈,NaN,I2,음식,I201,한식,I20103,족발/보쌈,I56111,한식 일반 음식점업,11,서울특별시,11680,강남구,11680700,세곡동,1168011100,세곡동,1168011100105870000,1,대지,587,NaN,서울특별시 강남구 세곡동 587,1.168042e+11,서울특별시 강남구 헌릉로569길,9.0,NaN,1168011100105870000000001,강남지웰파인즈,서울특별시 강남구 헌릉로569길 9,135190,6376,NaN,1,NaN,127.100762,37.466785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466007,MA0101202406A0446732,마장동,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,한식 일반 음식점업,11,서울특별시,11740,강동구,11740530,명일1동,1174010100,명일동,1174010100103120216,1,대지,312,216.0,서울특별시 강동구 명일동 312-216,1.174042e+11,서울특별시 강동구 고덕로38길,39.0,17.0,1174010100103120216019228,프라임빌딩,서울특별시 강동구 고덕로38길 39-17,134830,5257,NaN,1,NaN,127.143688,37.552723
466010,MA0101202406A0492191,주막칼국수,NaN,I2,음식,I201,한식,I20105,국수/칼국수,I56111,한식 일반 음식점업,11,서울특별시,11305,강북구,11305555,송천동,1130510100,미아동,1130510100100620039,1,대지,62,39.0,서울특별시 강북구 미아동 62-39,1.130541e+11,서울특별시 강북구 솔샘로68길,34.0,NaN,1130510100100620039025800,NaN,서울특별시 강북구 솔샘로68길 34,142805,1205,NaN,1,NaN,127.028835,37.615637
466012,MA0101202406A0492204,오빠네제육,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56111,한식 일반 음식점업,11,서울특별시,11350,노원구,11350640,상계2동,1135010500,상계동,1135010500101810017,1,대지,181,17.0,서울특별시 노원구 상계동 181-17,1.135041e+11,서울특별시 노원구 상계로12길,68.0,NaN,1135010500101810017007598,NaN,서울특별시 노원구 상계로12길 68,139816,1704,NaN,1,NaN,127.070533,37.655456
466014,MA0101202406A0493777,명태어장쭈갑골신월교육매장,NaN,I2,음식,I201,한식,I20112,해산물 구이/찜,I56114,한식 해산물 요리 전문점,11,서울특별시,11470,양천구,11470610,신월6동,1147010300,신월동,1147010300110020001,1,대지,1002,1.0,서울특별시 양천구 신월동 1002-1,1.147031e+11,서울특별시 양천구 신월로,120.0,NaN,1147010300110020001009492,레미앙아파트,서울특별시 양천구 신월로 120,158848,8047,NaN,NaN,NaN,126.837247,37.516116
466017,MA0101202406A0482676,이문족발,NaN,I2,음식,I201,한식,I20103,족발/보쌈,I56111,한식 일반 음식점업,11,서울특별시,11230,동대문구,11230740,이문1동,1123011000,이문동,1123011000103050079,1,대지,305,79.0,서울특별시 동대문구 이문동 305-79,1.123041e+11,서울특별시 동대문구 휘경로2길,5.0,12.0,1123011000103050079003718,NaN,서울특별시 동대문구 휘경로2길 5-12,130831,2441,NaN,1,NaN,127.061632,37.595376

In [148]:
df['구'] = df["도로명주소"].apply(lambda x : x.split()[1])
df['구'].value_counts(normalize=True)

구
강남구     0.119775
서초구     0.072857
송파구     0.062289
마포구     0.056240
영등포구    0.053879
강서구     0.048290
중구      0.047890
종로구     0.040153
관악구     0.036164
금천구     0.034561
구로구     0.034391
강동구     0.034142
광진구     0.033810
성동구     0.032498
동대문구    0.030919
은평구     0.030031
용산구     0.029988
성북구     0.027924
중랑구     0.027679
양천구     0.027630
노원구     0.027115
서대문구    0.025540
동작구     0.024267
강북구     0.023482
도봉구     0.018488
Name: proportion, dtype: float64

In [153]:
df.groupby(['구', '상권업종중분류명'], as_index=False)[['상권업종소분류명']].count().to_excel(
    '../data/smallmarket/cnt2.xlsx'
)

In [158]:
seoul = pd.read_csv("../data/smallmarket/소상공인시장진흥공단_상가(상권)정보_서울_202409.csv", encoding='utf-8', low_memory=False)

seoul['구'] = seoul["도로명주소"].apply(lambda x : x.split()[1])

seoul.groupby(['구', '상권업종대분류명'], as_index=False)[['상권업종소분류명']].count().sort_values(by=['구','상권업종소분류명'],
                                                                                  ascending=[True,False]).to_excel("./result2.xlsx")

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [ ]:

tmp_list = []
for idx, file in enumerate([f for f in os.listdir("../data/smallmarket") if f.endswith('.csv')]):
    print(idx)
    tmp_list.append(pd.read_csv(f"../data/smallmarket/{file}", encoding='utf-8', low_memory=False))

In [156]:
df['상권업종대분류명'].unique()

array(['과학·기술', '음식', '소매', '시설관리·임대', '교육', '숙박', '부동산', '수리·개인',
       '예술·스포츠', '보건의료'], dtype=object)

In [159]:
상권 = pd.concat(tmp_list, ignore_index=True)

In [160]:
상권

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0091348,아이에프엠,NaN,M1,과학·기술,M105,광고,M10501,광고 대행업,M71310,광고 대행업,48,경상남도,48127,창원시 마산회원구,48127560,양덕1동,4812710500,양덕동,4812710500100150027,1,대지,15.0,27.0,경상남도 창원시 마산회원구 양덕동 15-27,4.812748e+11,경상남도 창원시 마산회원구 양덕북12길,113.0,NaN,4812710500100150027013799,경민인터빌,경상남도 창원시 마산회원구 양덕북12길 113,630810.0,51364,NaN,1,NaN,128.583846,35.231915
1,MA010120220805430827,부림옷수선,NaN,S2,수리·개인,S206,기타 가정용품 수리,S20601,의류/이불 수선업,S95391,의복 및 기타 가정용 직물제품 수리업,48,경상남도,48125,창원시 마산합포구,48125630,오동동,4812511700,부림동,4812511700100320001,1,대지,32.0,1.0,경상남도 창원시 마산합포구 부림동 32-1,4.812520e+11,경상남도 창원시 마산합포구 315대로,352.0,NaN,4812511700100320444033486,부림상가,경상남도 창원시 마산합포구 315대로 352,631859.0,51730,NaN,2,NaN,128.573478,35.205797
2,MA010120220805430854,성모쑥뜸방,NaN,Q1,보건의료,Q104,기타 보건,Q10402,유사 의료업,S96999,그 외 기타 달리 분류되지 않은 개인 서비스업,48,경상남도,48170,진주시,48170555,성북동,4817011300,봉곡동,4817011300100100009,1,대지,10.0,9.0,경상남도 진주시 봉곡동 10-9,4.817033e+11,경상남도 진주시 진주성로,74.0,1.0,4817011300100100009003624,NaN,경상남도 진주시 진주성로 74-1,660040.0,52749,NaN,2,NaN,128.076649,35.196313
3,MA0101202210A0087932,원탑공인중개사사무소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,부동산 중개 및 대리업,48,경상남도,48129,창원시 진해구,48129580,석동,4812914000,석동,4812914000101860004,1,대지,186.0,4.0,경상남도 창원시 진해구 석동 186-4,4.812948e+11,경상남도 창원시 진해구 석동로30번길,10.0,NaN,4812914000101860004004349,NaN,경상남도 창원시 진해구 석동로30번길 10,645280.0,51660,NaN,1,NaN,128.702613,35.153600
4,MA010120220805431535,오미당꽈배기,NaN,I2,음식,I210,기타 간이,I21001,빵/도넛,I56191,제과점업,48,경상남도,48250,김해시,48250630,장유3동,4825013200,장유동,4825013200108260004,1,대지,826.0,4.0,경상남도 김해시 장유동 826-4,4.825034e+11,경상남도 김해시 율하6로,56.0,NaN,4825013200108260004000001,NaN,경상남도 김해시 율하6로 56,621340.0,51020,NaN,1,NaN,128.824132,35.171836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2389482,MA0101202406A0476645,수연식당,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,한식 일반 음식점업,26,부산광역시,26350,해운대구,26350580,반여2동,2635010300,반여동,2635010300112910820,1,대지,1291.0,820.0,부산광역시 해운대구 반여동 1291-820,2.635031e+11,부산광역시 해운대구 재반로,207.0,1.0,2635010300112910820017224,NaN,부산광역시 해운대구 재반로 207-1,612814.0,48029,NaN,2,NaN,129.130625,35.195837
2389483,MA0101202406A0482972,페스티발가라오케,NaN,I2,음식,I211,주점,I21104,요리 주점,I56219,기타 주점업,26,부산광역시,26350,해운대구,26350530,중1동,2635010600,중동,2635010600113930005,1,대지,1393.0,5.0,부산광역시 해운대구 중동 1393-5,2.635031e+11,부산광역시 해운대구 구남로,29.0,NaN,2635010600113930005005730,NaN,부산광역시 해운대구 구남로 29,612847.0,48095,NaN,4,NaN,129.161026,35.161522
2389484,MA0101202406A0471221,웰컴투뮤즈월드,NaN,P1,교육,P107,교육 지원,P10701,교육컨설팅업,P85701,교육관련 자문 및 평가업,26,부산광역시,26230,부산진구,26230520,부전2동,2623010300,부전동,2623010300102260001,1,대지,226.0,1.0,부산광역시 부산진구 부전동 226-1,2.623042e+11,부산광역시 부산진구 중앙대로680번길,22.0,NaN,2623010300102260001005883,NaN,부산광역시 부산진구 중앙대로680번길 22,614846.0,47296,NaN,NaN,NaN,129.060463,35.153214
2389485,MA0101202406A0497602,슈아브,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,26,부산광역시,26140,서구,26140630,초장동,2614011900,초장동,2614011900100540003,1,대지,54.0,3.0,부산광역시 서구 초장동 54-3,2.614030e+11,부산광역시 서구 구덕로,147.0,NaN,2614011900100540003000245,NaN,부산광역시 서구 구덕로 147,602834.0,49245,NaN,2,NaN,129.020472,35.097986
2389486,MA0101202406A0470616,공동법률사무소문정,NaN,M1,과학·기술,M103,법무관련,M10301,변호사,M71101,변호사업,26,부산광역시,26470,연제구,26470610,거제1동,2647010100,거제동,2647010100114920003,1,대지,1492.0,3.0,부산광역시 연제구 거제동 1492-3,2.647042e+11,부산광역시 연제구 법원남로15번길,12.0,NaN,2647010100114920003019273,대한타워빌딩,부산광역시 연제구 법원남로15번길 12,611730.0,47511,NaN,7,NaN,129.073684,35.190460