Problem 1:
- Make a dataframe where colums have the average departure and arrival delay time for each destination airport from each origin points.

Problem 2:
- Count the delayed flights for each destination airport (ArrDelay > 5 minutes). Print airports which have 2000 or more delayed flights. (Columns: Dest (Destination Airport), ArrDelay (delays greater than 5 minutes))

Problem 3:
- Count cancellations, diversions and airs without cancellation and diverts for each destination airport.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

hflight = pd.read_csv(
    './data/hflight.csv'
)

In [5]:
mask = hflight['ArrDelay'] >= 5 

hflight.isnull().sum()

tmp1 = hflight.loc[mask, :].groupby(['Dest'])['Year'].count()

mask2 = tmp1 >= 2000
tmp1[mask2].index

hflight2 = hflight[hflight.Dest.isin(tmp1[mask2].index)].copy()

In [ ]:
%load_ext sql
%reload_ext sql

%config SqlMagic.autocommit=False 
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

%sql mysql://dongik:dongik@localhost:3306/pandas_tutorial

In [ ]:

%sql SELECT Origin, Dest, avg(DepDelay), avg(ArrDelay)\
FROM flight \
GROUP BY Origin, Dest limit 5;

In [ ]:
%sql SELECT Origin, Dest, round(avg(DepDelay),2) DepDelay , round(avg(ArrDelay),2) ArrDelay\
FROM flight \
GROUP BY Origin, Dest limit 5;

In [ ]:
%sql select Dest, count(Year) as cnt from flight where ArrDelay >= 5 group by Dest having cnt >= 2000

In [ ]:
# %sql CREATE VIEW flight2 AS  \
#     select * from flight where Dest in \
#         (select Dest from (select Dest, count(Year) as cnt \
#         from flight \
#      where ArrDelay >= 5 \
#      GROUP by Dest \
#      having cnt >= 2000) \
#      a)

In [ ]:
# %sql select * from flight where Dest in \
#         (select Dest from (select Dest, count(Year) as cnt \
#         from flight \
#      where ArrDelay >= 5 \
#      GROUP by Dest \
#      having cnt >= 2000) \
#      a)

In [ ]:
import json
from sqlalchemy import create_engine

DB = "pandas_tutorial"

with open('/home/dongik/src/config.json', 'r') as config_file:
    config = json.load(config_file)['mysql'][DB]
    
username = config['username']
password = config['password']
host = config['host']
port = config['port']
database = 'pandas_tutorial'

connection_string = f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}'

engine = create_engine(connection_string)

try:
    with engine.connect() as connection:
        print("Database connection successful!")
except Exception as e:
    print(f"Database connection failed: {e}")
    
hflight.to_sql("flight", if_exists='replace', con=engine)

In [3]:
from toolkits.scrollable import display_dataframe as dp

# Ans 1
ans = hflight.groupby(['Origin', 'Dest'])[['ArrDelay', 'DepDelay']].mean()
dp(ans)

In [ ]:
tmp = hflight[hflight['ArrDelay'] >= 5].groupby(['Origin', 'Dest'])[['ArrDelay']].agg(['count']).reset_index()
tmp.columns = ['Origin', 'Dest', 'Cnt']
tmp = tmp[tmp['Cnt'] > 2000]
dp(tmp)

In [ ]:
tmp.columns = ['Dest', 'Count']
ans2 = tmp[tmp['Count'] >= 2000]['Dest']
ans2.unique()

In [ ]:

mask = hflight['ArrDelay'] >= 5 

hflight.isnull().sum()

tmp1 = hflight.loc[mask, :].groupby(['Dest'])['Year'].count()

mask2 = tmp1 >= 2000
tmp1[mask2].index

# hflight2 = hflight[hflight.Dest.isin(tmp1[mask2].index)].copy()

# hflight2

In [8]:
hflight['Cancelled'].unique() #array([0, 1])
hflight['Diverted'].unique()
tmp = hflight.groupby(['Origin', 'Dest'])[['Cancelled', 'Diverted']].agg(['sum',]).reset_index()
tmp.columns = ['Origin', 'Dest', 'Cancelled_count', 'Diverted_count']
tmp
tmp1 = hflight.groupby(['Origin', 'Dest'])[['FlightNum']].agg(['count']).reset_index()
tmp1.columns = ['Origin', 'Dest', 'Air']
tmp1
ans3 = pd.merge(tmp, tmp1, on=['Origin', 'Dest'], how='outer')
ans3['Air'] = ans3['Air'] - ans3['Cancelled_count'] - ans3['Diverted_count']
ans3.columns = ['Origin', "Dest", 'Cancelled', 'Diverted', 'Air']
dp(ans3.groupby(['Origin', 'Dest']).sum())

In [ ]:
tmp3 = pd.concat([hflight2.groupby(['Dest'])[['Year']].count(), 
           hflight2.groupby(['Dest'])[['Cancelled']].sum(),
           hflight2.groupby(['Dest'])[['Diverted']].sum()], axis=1)

tmp3

In [6]:
tmp3 = pd.concat([hflight2.groupby(['Dest'])[['Year']].count(), 
           hflight2.groupby(['Dest'])[['Cancelled']].sum(),
           hflight2.groupby(['Dest'])[['Diverted']].sum()], axis=1)


tmp3['air'] = tmp3.apply(lambda x : x[0] - x[1] - x[2] , axis=1)
dp(tmp3)

/tmp/ipykernel_10930/3063831719.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  tmp3['air'] = tmp3.apply(lambda x : x[0] - x[1] - x[2] , axis=1)