Problem 1:
- Make a dataframe where colums have the average departure and arrival delay time for each destination airport from each origin points.

Problem 2:
- Count the delayed flights for each destination airport (ArrDelay > 5 minutes). Print airports which have 2000 or more delayed flights. (Columns: Dest (Destination Airport), ArrDelay (delays greater than 5 minutes))

Problem 3:
- Count cancellations, diversions and airs without cancellation and diverts for each destination airport.

In [3]:
import pandas as pd

hflight = pd.read_csv(
    './data/hflight.csv'
)

In [4]:
# Ans 1
hflight.groupby(['Origin', 'Dest'])[['ArrDelay', 'DepDelay']].mean()

              ArrDelay   DepDelay
Origin Dest
HOU    ABQ    6.000987  11.581854
       ATL    6.810014   9.129112
       AUS    9.274145  12.188736
       BHM    6.672540  15.014599
       BKG  -16.233645  -3.201835
...                ...        ...
IAH    TUL    5.482379   5.738174
       TUS    7.801680   7.783871
       TYS   11.365915  10.170549
       VPS   12.457176  12.338691
       XNA    6.896277   6.690685

[149 rows x 2 columns]

In [5]:
tmp = hflight[hflight['ArrDelay'] < 5].groupby(['Origin', 'Dest'])[['ArrDelay']].agg(['count']).reset_index()
tmp.columns = ['Origin', 'Dest', 'Count']
ans2 = tmp[tmp['Count'] >= 2000]['Dest']
ans2.unique()

array(['DAL', 'MSY', 'ATL', 'AUS', 'CLT', 'CRP', 'DEN', 'DFW', 'EWR',
       'LAX', 'ORD', 'PHX'], dtype=object)

In [6]:
hflight['Cancelled'].unique() #array([0, 1])
hflight['Diverted'].unique()
tmp = hflight.groupby(['Origin', 'Dest'])[['Cancelled', 'Diverted']].agg(['sum',]).reset_index()
tmp.columns = ['Origin', 'Dest', 'Cancelled_count', 'Diverted_count']
tmp
tmp1 = hflight.groupby(['Origin', 'Dest'])[['FlightNum']].agg(['count']).reset_index()
tmp1.columns = ['Origin', 'Dest', 'Air']
tmp1
ans3 = pd.merge(tmp, tmp1, on=['Origin', 'Dest'], how='outer')
ans3['Air'] = ans3['Air'] - ans3['Cancelled_count'] - ans3['Diverted_count']
ans3.columns = ['Origin', "Dest", 'Cancelled', 'Diverted', 'Air']
ans3

    Origin Dest  Cancelled  Diverted   Air
0      HOU  ABQ          5         1  1013
1      HOU  ATL         63        10  2816
2      HOU  AUS          5         2  1667
3      HOU  BHM          6         4   681
4      HOU  BKG          2         1   107
..     ...  ...        ...       ...   ...
144    IAH  TUL         37         2  1816
145    IAH  TUS         15         2  1548
146    IAH  TYS          8         5  1197
147    IAH  VPS         10         6   864
148    IAH  XNA         34        10  1128

[149 rows x 5 columns]