Problem 1:
- Make a dataframe where colums have the average departure and arrival delay time for each destination airport from each origin points.

Problem 2:
- Count the delayed flights for each destination airport (ArrDelay > 5 minutes). Print airports which have 2000 or more delayed flights. (Columns: Dest (Destination Airport), ArrDelay (delays greater than 5 minutes))

Problem 3:
- Count cancellations, diversions and airs without cancellation and diverts for each destination airport.

In [6]:
import pandas as pd
pd.set_option('display.max_columns', None)

hflight = pd.read_csv(
    './data/hflight.csv'
)

In [2]:
# Ans 1
hflight.groupby(['Origin', 'Dest'])[['ArrDelay', 'DepDelay']].mean()

              ArrDelay   DepDelay
Origin Dest
HOU    ABQ    6.000987  11.581854
       ATL    6.810014   9.129112
       AUS    9.274145  12.188736
       BHM    6.672540  15.014599
       BKG  -16.233645  -3.201835
...                ...        ...
IAH    TUL    5.482379   5.738174
       TUS    7.801680   7.783871
       TYS   11.365915  10.170549
       VPS   12.457176  12.338691
       XNA    6.896277   6.690685

[149 rows x 2 columns]

In [3]:
tmp = hflight[hflight['ArrDelay'] < 5].groupby(['Origin', 'Dest'])[['ArrDelay']].agg(['count']).reset_index()
tmp.columns = ['Origin', 'Dest', 'Count']
ans2 = tmp[tmp['Count'] >= 2000]['Dest']
ans2.unique()

array(['DAL', 'MSY', 'ATL', 'AUS', 'CLT', 'CRP', 'DEN', 'DFW', 'EWR',
       'LAX', 'ORD', 'PHX'], dtype=object)

In [4]:
hflight['Cancelled'].unique() #array([0, 1])
hflight['Diverted'].unique()
tmp = hflight.groupby(['Origin', 'Dest'])[['Cancelled', 'Diverted']].agg(['sum',]).reset_index()
tmp.columns = ['Origin', 'Dest', 'Cancelled_count', 'Diverted_count']
tmp
tmp1 = hflight.groupby(['Origin', 'Dest'])[['FlightNum']].agg(['count']).reset_index()
tmp1.columns = ['Origin', 'Dest', 'Air']
tmp1
ans3 = pd.merge(tmp, tmp1, on=['Origin', 'Dest'], how='outer')
ans3['Air'] = ans3['Air'] - ans3['Cancelled_count'] - ans3['Diverted_count']
ans3.columns = ['Origin', "Dest", 'Cancelled', 'Diverted', 'Air']
ans3

    Origin Dest  Cancelled  Diverted   Air
0      HOU  ABQ          5         1  1013
1      HOU  ATL         63        10  2816
2      HOU  AUS          5         2  1667
3      HOU  BHM          6         4   681
4      HOU  BKG          2         1   107
..     ...  ...        ...       ...   ...
144    IAH  TUL         37         2  1816
145    IAH  TUS         15         2  1548
146    IAH  TYS          8         5  1197
147    IAH  VPS         10         6   864
148    IAH  XNA         34        10  1128

[149 rows x 5 columns]

In [7]:
hflight

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted
0,2011,1,1,6,1400.0,1500.0,AA,428,N576AA,60.0,40.0,-10.0,0.0,IAH,DFW,224,7.0,13.0,0,NaN,0
1,2011,1,2,7,1401.0,1501.0,AA,428,N557AA,60.0,45.0,-9.0,1.0,IAH,DFW,224,6.0,9.0,0,NaN,0
2,2011,1,3,1,1352.0,1502.0,AA,428,N541AA,70.0,48.0,-8.0,-8.0,IAH,DFW,224,5.0,17.0,0,NaN,0
3,2011,1,4,2,1403.0,1513.0,AA,428,N403AA,70.0,39.0,3.0,3.0,IAH,DFW,224,9.0,22.0,0,NaN,0
4,2011,1,5,3,1405.0,1507.0,AA,428,N492AA,62.0,44.0,-3.0,5.0,IAH,DFW,224,9.0,9.0,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227491,2011,12,6,2,1818.0,2111.0,WN,1191,N284WN,113.0,97.0,-9.0,8.0,HOU,TPA,781,5.0,11.0,0,NaN,0
227492,2011,12,6,2,2047.0,2334.0,WN,1674,N366SW,107.0,94.0,4.0,7.0,HOU,TPA,781,4.0,9.0,0,NaN,0
227493,2011,12,6,2,912.0,1031.0,WN,127,N777QC,79.0,61.0,-4.0,-3.0,HOU,TUL,453,4.0,14.0,0,NaN,0
227494,2011,12,6,2,656.0,812.0,WN,621,N727SW,76.0,64.0,-13.0,-4.0,HOU,TUL,453,3.0,9.0,0,NaN,0
227495,2011,12,6,2,1600.0,1713.0,WN,1597,N745SW,73.0,59.0,-12.0,0.0,HOU,TUL,453,3.0,11.0,0,NaN,0